### ISSUE TITLE
Automatically approve all reviews

### ISSUE THREAD

**Issue by ghost** [sigalevoa/ironlab_simple_reviews#1]
Hello,
First thanks for this great plugin. It works well.
Quick question. Is it possible to somehow add the functionality to automatically approve every review posted?
I am asking about this because when people submit the review they don't see it on the website right away so they might try to submit another review. This also shows that we actually review every review.
I would like to stay neutral and just let everyone write whatever review they would like without alerting them that we actually have to approve their review.
I know this is not for everyone but I think it brings up the credibility of the reviews. Otherwise people will just refuse to approve negative reviews and that is not good.

Thanks and hopefully it's not too much work to update this plugin to support this functionality.
Kind regards

**Comment by sigalevoa** [comment]
Hi. I will add a function that allows you to display all messages without moderation in the near future

**Comment by sigalevoa** [comment]
plugin updated

**Comment by ghost** [comment]
Hey,
First thanks for the update. Tested and it works great.
Quick question. When someone submits the review, the review is not displayed until you refresh the page. For better user experience should the plugin handle this on submit (refreshing the page) or should I just add something to refresh the page on submit (some html code). I am very new at october cms so apologies for silly question. Let me know.
Other than that thank you for your work. Much appreciated. If everyone was so responsive and engaging as yourself on october cms plugins it would be an amazing experience for newcomers like me. You are a star!

EDIT: Something I noticed on the backed. Automatically approved reviews are not "displayed" as published on backed. Did you do this intentionally or?
https://imgur.com/jkap9mS
https://imgur.com/TroDB3U
